### ISSUE TITLE
The link in the Dummy Head doesn't work

### ISSUE THREAD

**Issue by bydavid** [codepath/compsci_guides#3]
Clicking the below link takes me to an internal server error, on safari.
* http://www.eternallyconfuzzled.com/tuts/datastructures/jsw_tut_linklist.aspx

**Comment by curiousjazz77** [comment]
Here's the archived version of that link that still has the content: https://web.archive.org/web/20180227180712/http://www.eternallyconfuzzled.com/tuts/datastructures/jsw_tut_linklist.aspx
