### ISSUE TITLE
bug: screen width for mobile devices is poor

### ISSUE THREAD

**Issue by kev-odin** [codepath/compsci_guides#6]
@SamanthaCP I am running into issues with the front end application for mobile devices. How can we improve the rendered information to be mobile first priority?

Thanks!

Edit:
![image](https://user-images.githubusercontent.com/60195141/199333347-aee175c1-5ae5-47cb-b40c-732b2380c7a8.png)

Device used: iPhone 11 with Safari web browser.

**Comment by nesquena** [comment]
Hi Kevin,

Thanks for the report. Are you seeing something different then this on pages. 

I booted up Safari, went to the guides and I saw this!

[image](https://user-images.githubusercontent.com/6511/199334160-842576e0-0240-4aa2-95b1-0c352267da5e.jpeg)![image](https://user-images.githubusercontent.com/6511/199334171-b35ebb52-031d-487d-b170-26619e704dfa.jpeg)![image](https://user-images.githubusercontent.com/6511/199334185-704eb216-c4a6-48d1-94fd-ed4dfb399574.jpeg)

Are you seeing the same content zoom by default? Are you referring to after pinching out on the page to zoom out, and the way the table of contents on the right renders?

If I hid that right TOC on mobile entirely, perhaps that would resolve the issue?

**Comment by kev-odin** [comment]
Right. I was viewing the content in landscape mode. The TOC is pushed to the right side?

**Comment by nesquena** [comment]
> Right. I was viewing the content in landscape mode. The TOC is pushed to the right side?

Ah in landscape got it, that's helpful. I'll make a few basic tweaks to avoid that clipping issue in landscape. Thanks for the report.

**Comment by kev-odin** [comment]
Ah thanks! btw what is the best way to contribute to this repo? I am prepping for an interview and thought I would help update the content and outdated links. 

Fork and Pull Request? OR Edit the Wiki directly?

It was not clear in the `contributing.md`

**Comment by nesquena** [comment]
> Ah thanks! btw what is the best way to contribute to this repo? I am prepping for an interview and thought I would help update the content and outdated links. 
> 
> 
> 
> Fork and Pull Request? OR Edit the Wiki directly?
> 
> 
> 
> It was not clear in the `contributing.md`

Sure no problem. 

I'll let Samantha respond re how she prefers contributions to come into this now. One safe option though is to raise an issue here with a link to the revised copy for a page (as a GitHub gist or hackmd document you link in the issue)

**Comment by nesquena** [comment]
@kev-odin Also, I think I've fixed it now on mobile, can you confirm this is resolved?

**Comment by kev-odin** [comment]
> @kev-odin Also, I think I've fixed it now on mobile, can you confirm this is resolved?

Looks good to me! Thank you for a quick fix. 

![image](https://user-images.githubusercontent.com/60195141/199358427-17dc24e7-d6ff-44db-b4ec-d33b3581b245.png)

**Comment by nesquena** [comment]
> > @kev-odin Also, I think I've fixed it now on mobile, can you confirm this is resolved?
> 
> Looks good to me! Thank you for a quick fix. 
> 
> ![image](https://user-images.githubusercontent.com/60195141/199358427-17dc24e7-d6ff-44db-b4ec-d33b3581b245.png)

Great thanks, closing!

**Comment by SamanthaCP** [comment]
> > Ah thanks! btw what is the best way to contribute to this repo? I am prepping for an interview and thought I would help update the content and outdated links.
> > Fork and Pull Request? OR Edit the Wiki directly?
> > It was not clear in the `contributing.md`
> 
> Sure no problem.
> 
> I'll let Samantha respond re how she prefers contributions to come into this now. One safe option though is to raise an issue here with a link to the revised copy for a page (as a GitHub gist or hackmd document you link in the issue) or if it is a small change, put the requested changes into the issue body

Hi Kevin!

Thank you so much for lifting up this issue! I agree with Nathan that the best way to lift up any feedback would be opening up an issue in this repo, tagging me, and providing the link to the page. From there I will be able to triage the request and update the content appropriately.

**Comment by kev-odin** [comment]
> Hi Kevin!
> 
> Thank you so much for lifting up this issue! I agree with Nathan that the best way to lift up any feedback would be opening up an issue in this repo, tagging me, and providing the link to the page. From there I will be able to triage the request and update the content appropriately.

@SamanthaCP  How does the site regularly update content? Is the information from the GitHub repo pushed to the front-end?

I made some changes to Stacks and Queue from the wiki page. Just want to make sure that I understand the process before I continue to update the content.

Cheers,
Kevin

**Comment by nesquena** [comment]
> > Hi Kevin!
> 
> > 
> 
> > Thank you so much for lifting up this issue! I agree with Nathan that the best way to lift up any feedback would be opening up an issue in this repo, tagging me, and providing the link to the page. From there I will be able to triage the request and update the content appropriately.
> 
> 
> 
> @SamanthaCP  How does the site regularly update content? Is the information from the GitHub repo pushed to the front-end?
> 
> 
> 
> I made some changes to Stacks and Queue from the wiki page. Just want to make sure that I understand the process before I continue to update the content.
> 
> 
> 
> Cheers,
> 
> Kevin

The frontend is auto synced with the default branch of the GitHub wiki. Commits made to the wiki content repo (Wiki tab) on this repo is then automatically pushed to the custom front end.
