### ISSUE TITLE
Linked List guides need edits to replace "dummy" with "temp"

### ISSUE THREAD

**Issue by juliekang** [codepath/compsci_guides#9]
According to the [Temp Head Technique page](https://guides.codepath.org/compsci/Temp-Head), references to "dummy" should be replaced with "temp." In that spirit, the [Linked List guides](https://github.com/codepath/compsci_guides/wiki/Remove-Nth-Node-from-End-of-List) contain a lot of references to dummy nodes and heads, and should be updated to reflect that.

Happy to pitch in if you'd like!

**Comment by LeWiz24** [comment]
@juliekang Thank you creating this issue! Fixed.
